### PR TITLE
Changed Q_Flow to Q_flow

### PR DESCRIPTION
**Pull request by mwetter**
This corrects the variable name.

### CODE REVIEW

**Comment by kbenne** [comment]
Thanks for digging into this!

**Comment by amirroth** [comment]
What about `Qflow` instead of `Linkages`?

**Comment by kbenne** [comment]
That is an excellent name!

**Comment by mwetter** [comment]
Happy to discuss `Linkages` on another thread with Antoine. We had `Qflow` as an option earlier but thought it does not capture the control sequence selection and configuration aspect.

**Pull request merged**
