### PR TITLE
Compiler hook

### PR DESCRIPTION
**Pull request by lefticus**
@kbenne Here is another branch that was languishing.

But that the moment I cannot recall what the point of this branch was, so we might need to review it together.

I think the ideas was to get end-to-end through the integrated LLVM compiler, but it doesn't seem to have any additional tests, or I'm missing something in my review of it.

### CODE REVIEW

**Comment by lefticus** [comment]
@kbenne update: I needed to build with "Enable Modelica Compiler" to see the changed tests.

**Comment by kbenne** [comment]
ah yes. of course. Next thing is that we're going to need more horsepower as I think that option adds notable build time.

**Comment by lefticus** [comment]
Seems I have a few boost related build issues to sort out (since we removed boost), I'll report back once it's building / working again.

**Comment by lefticus** [comment]
I think this is good, I attempted to just add a ci build process for it.

**Pull request closed without merging**
